---
- name: BBuddy Server
  hosts: all
  vars_files:
    - src/main/resources/application.yml
  any_errors_fatal: true
  roles:
    - jdk8
    - gradle
    - role: mysql
      mysql:
        database: bbuddytest
        user: "{{ spring.datasource.username }}"
        password: "{{ spring.datasource.password }}"
    - role: mysql
      mysql:
        database: bbuddydev
        user: "{{ spring.datasource.username }}"
        password: "{{ spring.datasource.password }}"
    - firefox

- name: BBuddy CI
  hosts: bbuddy_ci_servers
  any_errors_fatal: true
  roles:
    - role: jenkins
      jenkins:
        port: 8000
